version: '1.0'
services:
  nodejs:
    build: ./
    ports:
      - "4000:4000"
    volumes:
      - ./://home/node/app
      - /home/node/app/dist/
      - /home/node/app/node_modules
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  dist:
